### ISSUE TITLE
Not working for array of objects with strings

### ISSUE THREAD

**Issue by pinglinh** [taw/finder-sort#1]
If I have an array of objects with strings, it doesn't work

**Comment by taw** [comment]
Do you need to sort by just one key from those objects, like with this sorting by `.name`?

```
let data = [
  {name: "cat1.jpg", color: "white"},
  {name: "cat11.jpg", color: "brown"},
  {name: "cat9.jpg", color: "pink"},
]
```

Or do you need some more complicated sorting?

**Comment by pinglinh** [comment]
yeah just by one key for now

**Comment by taw** [comment]
Try it now.

**Comment by taw** [comment]
Confirmed fixed
